# Bảng màu cơ bản (ANSI colors)
color0 #000000
color1 #f72585
color2 #52b788
color3 #f4a261
color4 #4361ee
color5 #7209b7
color6 #4cc9f0
color7 #e0a9ff

# Bảng màu sáng (Bright ANSI colors)
color8 #382c4f
color9 #ff758f
color10 #74c69d
color11 #ffb703
color12 #560bad
color13 #b5179e
color14 #48cae4
color15 #f8f9fa

# Màu nền và chữ
background               #000000
foreground               #e5d4ff
selection_foreground     #0f0b14
selection_background     #433878

# Con trỏ (Cursor)
cursor                   #a370f0
cursor_text_color        #0f0b14
cursor_trail_color       #7209b7

# Đường viền cửa sổ (nếu có chia pane)
active_border_color      #7209b7
inactive_border_color    #2d2440

# Tab trên terminal
active_tab_foreground    #ffffff
active_tab_background    #7209b7
inactive_tab_foreground  #a370f0
inactive_tab_background  #16121d
