shell  /usr/bin/zsh
font_family Hack Nerd Font Regular
font_size 10.0
repaint_delay 10


background_opacity 0.95
background_blur 0

#theme

enabled_layouts grid
# active_border_color #00ffff

# QUAN TRỌNG: Để 'none' để nó dùng màu gốc của con trỏ (Màu xanh TokyoNight).
# Nếu bạn để màu khác, nó sẽ bị đè màu.
#cursor_trail_color none
#sync_to_monitor yes

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

# --- CẤU HÌNH HIỂU ỨNG MƯỢT MÀ (SMOOTH CURSOR) ---
# Bật tính năng vẽ khung hình động (animation) giúp con trỏ di chuyển trơn tru
enable_audio_bell no
visual_window_latin_characters yes

# Tăng tần số quét (repaint_delay) và đồng bộ (input_delay)
# Giảm repaint_delay xuống 1 hoặc 2 để cập nhật khung hình liên tục, 
# kết hợp với vệt trail sẽ tạo cảm giác mượt mà như lướt trên mặt nước.
repaint_delay 7
input_delay 1
sync_to_monitor no

# Định dạng con trỏ (tùy chọn)
#cursor_shape block
#cursor_blink_interval 0

# --- HIỆU ỨNG GHOST TRAIL (GIỮ NGUYÊN CỦA BẠN) ---
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
